services:
  app:
    image: my-fastify-app
    build:
      context: .
      target: ${NODE_ENV}

    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./src:/usr/app/src

    command: >
      sh -c "
      if [ ${NODE_ENV} = development ]; then
        yarn test && yarn run dev;
      else
        yarn run start;
      fi
      "